apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboard-services
  title: Create and Onboard a new react app
  description: A template to create and onboard a new react app
  tags:
    - nextjs
    - react
    - javascript
spec:
  owner: debabrata.panigrahi@harness.io
  type: service
  parameters:
    - title: Next.js app details
      required:
        - project_name
        - gitlab_repo
        - gitlab_org
      properties:
        project_name:
          title: Name of your new app
          type: string
          description: Unique name of the app          
        gitlab_repo:
          title: Name of the Gitlab repository
          type: string
          description: This will be the name of Repository on Gitlab
        gitlab_org:
          title: Name of the Gitlab Organisation
          type: string
          description: This will be the name of Organisation on Gitlab
        gitlab_token:
          title: Gitlab PAT
          type: string
          ui:widget: password
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Creating your react app
      action: trigger:harness-custom-pipeline
      input:
        url: "YOUR PIPELINE URL"
        inputset:
          project_name: ${{ parameters.project_name }}
          gitlab_repo: ${{ parameters.gitlab_repo }}
          gitlab_org: ${{ parameters.gitlab_org }}
          gitlab_token: ${{ parameters.gitlab_token }}
        apikey: ${{ parameters.token }}
    # The final step is to register our new component in the catalog.
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
