apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-new-service3
  description: Description of my new service
  annotations:
    backstage.io/techdocs-ref: dir:.
    pagerduty.com/integration-key: <sample-service-integration-key>
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://jira.com
      title: Jira project board
spec:
  type: service
  lifecycle: production
  owner: Demo_Group
  system: project-x
